coursework/cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove,
            name='cart_remove'),
    re_path(r'^place/$', views.cart_place_order,
            name='cart_place_order'),
]

coursework/coursework/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from work import views

app_name = 'work'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.product_list, name="welcome"),

    path("users/", include('users.urls')),
    path("cart/", include('cart.urls')),
    path('category/<int:category_id>/', views.category_products,
         name='category_products'),
    path('product/<int:product_id>/', views.product_detail,
         name='product_detail'),
    path("orders/", views.user_orders, name="user_orders"),
    path("search/", views.search_products, name="search_products"),
    re_path(r'^report_builder/', include('report_builder.urls')),
    path('admin_tools_stats/', include('admin_tools_stats.urls'))
    # path('cart/', views.product_list, name="cart"),

]

coursework/work/models.py
import re
from datetime import timedelta
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone


class Customers(models.Model):
    """Customers model"""

    class Meta:
        db_table = 'customers'
        managed = False
        verbose_name = "Покупатель"
        verbose_name_plural = "Покупатели"

    customer_id = models.AutoField(primary_key=True)
    customer_name = models.CharField(verbose_name="Имя", max_length=50,
                                     null=True, blank=True)
    customer_lastname = models.CharField(verbose_name="Фамилия", max_length=50,
                                         null=True, blank=True)
    customer_surename = models.CharField(verbose_name="Отчество",
                                         max_length=50, null=True, blank=True)
    customer_email = models.EmailField(verbose_name="Почта", max_length=100,
                                       unique=True)
    customer_phone = models.CharField(verbose_name="Телефон", max_length=15,
                                      null=True, blank=True)
    customer_datebirth = models.DateField(verbose_name="Дата рождения",
                                          null=True, blank=True)
    customer_password = models.CharField(verbose_name="Пароль", max_length=100,
                                         unique=True)
    customer_photo = models.TextField(verbose_name="Фотография", null=True,
                                      blank=True)

    def __str__(self):
        return f"{self.customer_lastname} {self.customer_name}"


class Addresses(models.Model):
    """Addresses model"""

    class Meta:
        db_table = 'addresses'
        managed = False
        verbose_name = "Адрес"
        verbose_name_plural = "Адреса"

    address_id = models.AutoField(primary_key=True)
    ad_customer = models.ForeignKey('users.User', on_delete=models.RESTRICT,
                                    db_column='ad_customer',
                                    verbose_name='ФИО покупателя')
    ad_country = models.CharField(verbose_name="Страна", max_length=100)
    ad_region = models.CharField(verbose_name="Регион/край", max_length=100)
    ad_city = models.CharField(verbose_name="Город", max_length=100)
    ad_street = models.CharField(verbose_name="Улица", max_length=100)
    ad_house = models.IntegerField(verbose_name="Дом")
    ad_building = models.IntegerField(verbose_name="Строение", null=True,
                                      blank=True)
    ad_apartment = models.IntegerField(verbose_name="Квартира", null=True,
                                       blank=True)
    ad_index = models.IntegerField(verbose_name="Индекс")


class Status(models.Model):
    """Status model"""

    class Meta:
        db_table = "status"
        managed = False
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"

    status_id = models.AutoField(primary_key=True)
    status_name = models.CharField(verbose_name="Статус заказа", max_length=20,
                                   unique=True)

    def __str__(self):
        return f"{self.status_name}"


class Categories(models.Model):
    """Categories model"""

    class Meta:
        db_table = 'categories'
        managed = False
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(verbose_name="Категория товара",
                                     max_length=70, unique=True)

    def __str__(self):
        return f"{self.category_name}"


class Products(models.Model):
    """Products model"""

    class Meta:
        db_table = "products"
        managed = False
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    product_id = models.AutoField(primary_key=True)
    prod_name = models.CharField(verbose_name="Название товара",
                                 max_length=100, unique=True)
    prod_description = models.TextField(verbose_name="Описание товара",
                                        null=True, blank=True)
    prod_photo = models.TextField(verbose_name="Изображение товара",
                                  null=True, blank=True)
    prod_amount = models.IntegerField(verbose_name="Количество товара",
                                      null=True, blank=True, default=0)
    prod_category = models.ForeignKey('Categories', on_delete=models.RESTRICT,
                                      db_column='prod_category',
                                      verbose_name='Категория товара')
    prod_sell_price = models.DecimalField(verbose_name="Цена продажи",
                                          max_digits=10, decimal_places=2,
                                          default=0.00)
    prod_supply_price = models.DecimalField(verbose_name="Цена поставки",
                                            max_digits=10, decimal_places=2,
                                            default=0.00)
    prod_photo_thumbnail = models.TextField(verbose_name="Изображение товара",
                                            null=True, blank=True)

    def __str__(self):
        return f"{self.prod_name}"

    def description(self):
        return self.prod_description[:40] + "..." \
            if self.prod_description else 'Описание отсутсвует'

    description.short_description = 'Описание товара'

    def link_on_photo(self):
        return self.prod_photo[:40] + "..." \
            if self.prod_photo else 'Ссылка отсутствует'

    link_on_photo.short_description = 'Ссылка на изображение'

    def convert(self, gdrive_url):
        file_id = gdrive_url.split('/d/')[1].split('/view')[0]
        return f'https://drive.google.com/uc?id={file_id}'

    def to_json(self):
        return {
            'product_id': self.product_id,
            'prod_name': self.prod_name,
            'prod_sell_price': str(self.prod_sell_price),
            'prod_photo': self.convert(str(self.prod_photo)),
        }

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_id': self.pk})


class Supplies(models.Model):
    """Supplies model"""

    class Meta:
        db_table = 'supplies'
        managed = False
        verbose_name = "Поставка"
        verbose_name_plural = "Поставки"

    supply_id = models.AutoField(primary_key=True)
    sup_product = models.ForeignKey('Products', on_delete=models.RESTRICT,
                                    db_column='sup_product',
                                    verbose_name='Название товара')
    sup_amount = models.IntegerField(verbose_name='Количество товара')


class Orders(models.Model):
    """Orders model"""

    class Meta:
        db_table = 'orders'
        managed = False
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    order_id = models.AutoField(primary_key=True)
    order_date = models.DateTimeField(verbose_name='Дата заказа',
                                      editable=False)
    ord_customer = models.ForeignKey('users.User', on_delete=models.RESTRICT,
                                     db_column='ord_customer',
                                     verbose_name='Покупатель')
    ord_status = models.ForeignKey('Status', on_delete=models.RESTRICT,
                                   db_column='ord_status',
                                   verbose_name='Статус')

    def save(self, *args, **kwargs):
        # При создании заказа устанавливаем дату и времени,
        # если она еще не установлена
        if not self.order_id or (
                self.ord_status.status_name == 'Ожидает оплаты' and
                'ord_status' in kwargs.get(
                'update_fields', [])):
            self.order_date = timezone.now() + timedelta(hours=7)
            self.order_date = self.order_date.strftime('%Y-%m-%d %H:%M:%S')
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.order_id}"


class OrderItems(models.Model):
    """OrderItems model"""

    class Meta:
        db_table = 'order_items'
        managed = False
        verbose_name = "Состав заказа"
        verbose_name_plural = "Состав заказов"
        unique_together = ('oi_order', 'oi_product')

    oi_id = models.AutoField(primary_key=True)
    oi_order = models.ForeignKey('Orders', on_delete=models.RESTRICT,
                                 db_column='oi_order',
                                 verbose_name='Номер заказа')
    oi_product = models.ForeignKey('Products', on_delete=models.RESTRICT,
                                   db_column='oi_product',
                                   verbose_name='Название товара')
    oi_amount = models.IntegerField(default=1,
                                    verbose_name='Количество единиц товара')


class ProfitReport(models.Model):
    class Meta:
        db_table = 'profit_report'
        managed = False
        verbose_name = "Прибыль"
        verbose_name_plural = "Прибыль"

    order_id = models.AutoField(primary_key=True)
    day = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    sum_profit = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateTimeField(editable=False)


class SalesGraphic(models.Model):
    class Meta:
        db_table = 'sales_graphic'
        managed = False
        verbose_name = "Продажи"
        verbose_name_plural = "Продажи"

    order_id = models.AutoField(primary_key=True)
    order_date = models.DateTimeField(editable=False)
    prod_name = models.CharField()
    category_name = models.CharField()
    oi_amount = models.IntegerField()


@receiver(post_save, sender=Supplies)
def increase_product_quantity(sender, instance, created, **kwargs):
    """Обновляет количество товара при добавлении поставки."""
    if created:
        product = instance.sup_product

coursework/work/views.py
from django.shortcuts import render, get_object_or_404
from .models import Products, Categories, Orders, OrderItems
from cart.forms import CartAddProductForm


def product_detail(request, product_id):
    product = get_object_or_404(Products, pk=product_id)
    max_quantity = product.prod_amount

    if request.user.is_authenticated:
        current_user = request.user
        order_id = Orders.objects.filter(
            ord_customer=current_user,
            ord_status__status_name='Временный').first()

        if order_id:
            try:
                order_item = OrderItems.objects.get(oi_order=order_id,
                                                    oi_product=product_id)
                max_quantity -= order_item.oi_amount
            except OrderItems.DoesNotExist:
                pass

    cart_product_form = CartAddProductForm(max_quantity,
                                           initial={'quantity': 1})

    return render(request, 'product_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'max_quantity': max_quantity})


def category_products(request, category_id):
    categories = categories_list()
    category = get_object_or_404(Categories, pk=category_id)
    products = Products.objects.filter(prod_category=category)
    return render(request, 'category_products.html',
                  {'category': category, 'products': products,
                   'categories': categories})


def categories_list():
    return Categories.objects.all()


def product_list(request):
    search_query = request.GET.get('q', '')
    if search_query:
        products = Products.objects.filter(name__icontains=search_query)
    else:
        products = Products.objects.all()
    categories = categories_list()
    return render(request, 'show_products.html',
                  {'products': products, 'categories': categories})


def user_orders(request):
    current_user = request.user
    orders = Orders.objects.filter(ord_customer=current_user).exclude(
        ord_status__status_name='Временный').order_by('-order_date')

    orders_data = []

    for order in orders:
        order_items = OrderItems.objects.filter(oi_order=order)
        items_data = []
        full_price = 0
        for item in order_items:
            items_data.append({
                'product_name': item.oi_product.prod_name,
                'prod_photo': item.oi_product.prod_photo_thumbnail,
                'price': item.oi_product.prod_sell_price,
                'total_price': item.oi_product.prod_sell_price*item.oi_amount,
                'amount': item.oi_amount
            })
            full_price += item.oi_product.prod_sell_price*item.oi_amount
        orders_data.append({
            'order_id': order.order_id,
            'order_date': order.order_date,
            # 'customer': order.ord_customer.username,
            # Замените на поле, которое содержит информацию о покупателе
            'status': order.ord_status.status_name,
            # Замените на поле, которое содержит название статуса заказа
            'items': items_data,
            'full_price': full_price
        })
    return render(request, 'user_orders.html', {'orders_data': orders_data})


def search_products(request):
    if request.method == 'GET':
        query = request.GET.get('query', '')
        results = Products.objects.filter(prod_name__icontains=query)
        return render(request, 'search_results.html',
                      {'results': results})

coursework/work/templates/work/category_products.html
{% load static %}
{% block content %}
{% include 'header.html' %}
<div class="custom-content">
    <h1>{{ category.category_name }}</h1>
    <div class="products">
        {% for product in products %}
        <div class="product">
            <img src="{{ product.prod_photo_thumbnail }}" alt="Картинка скоро появится">
            <div class="product-info">
                <p>{{ product.prod_name }}</p>
                <p>Цена: {{ product.prod_sell_price }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

coursework/work/templates/work/header.html
{% extends 'main.html' %}
{% block content %}
<div class="custom-content">
    <header>
        {% if user.is_authenticated %}
        <a href="{% url 'user' user.id %}">Профиль</a>
        {% else %}
        <a href="{% url 'login' %}">Войти</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'cart:cart_detail' %}">Корзина</a>
        {% else %}
        <a href="{% url 'login' %}?next={% url 'welcome' %}">Корзина</a>
        {% endif %}
    </header>

        <ul class="categories">
            <li class="category">
                <a href="{% url 'welcome' %}">Главная страница</a>
            </li>
            {% for category in categories %}
            <li class="category">
                <a href="{% url 'category_products' category.category_id %}">
                    {{ category.category_name }}</a>
            </li>
            {% endfor %}
        </ul>
<!--        <form id="search-form" method="get"-->
<!--              action="{% url 'search_products' %}">-->
<!--            {% csrf_token %}-->
<!--            <input type="text" id="q" name="q" placeholder="Поиск товаров">-->
<!--            <button type="submit">Поиск</button>-->
<!--        </form>-->
<!--        <div id="search-results"></div>-->

</div>
{% endblock  %}
<!--<script>-->
<!--    $(document).ready(function() {-->
<!--        $('#q').on('input', function() {-->
<!--            var query = $(this).val();-->
<!--            if (query.length >= 2) {-->
<!--                $.ajax({-->
<!--                    type: 'GET',-->
<!--                    url: '/search/',  // Замените на свой URL-путь к представлению поиска-->
<!--                    data: {'query': query,'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()},-->
<!--                    success: function(data) {-->
<!--                        $('#search-results').html(data);-->
<!--                    }-->
<!--                });-->
<!--            } else {-->
<!--                $('#search-results').html('');-->
<!--            }-->
<!--        });-->
<!--    });-->
<!--</script>-->

coursework/work/templates/work/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} aicen {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css"
          href="{% static 'work/css/main.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    <script></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

coursework/work/templates/work/product_detail.html
{% load static %}
{% block content %}
{% include 'header.html' %}
<div class="custom-content product-page">
    <div class="products">
        <img src="{{ product.prod_photo }}" alt="Картинка товара скоро появится" width="700" height="700">
        <h2>{{ product.prod_name }}</h2>
        <p class="description">{{ product.prod_description }}</p>
        <h3>Цена: {{ product.prod_sell_price }} ₽</h3>
        {% if user.is_authenticated %}
            {% if max_quantity > 0 %}
                <form action="{% url 'cart:cart_add' product.product_id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="В корзину">
                </form>
            {% else %}
                <p>Извините, товар закончился.</p>
            {% endif %}
        {% else %}
            <p>Для добавления товара в корзину, пожалуйста, <a href="{% url 'login' %}">войдите в систему</a>.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

coursework/work/templates/work/show_products.html
{% load static %}
{% block content %}
{% include 'header.html' %}
<div class="custom-content">
    <h1>Популярное</h1>
    <div class="products">
        {% for product in products %}
        <div class="product">
            <a href="{% url 'product_detail' product.product_id %}">
                <img src="{{ product.prod_photo_thumbnail }}"
                     alt="Картинка товара скоро появится">
                <div class="product-info">
                    <p>{{ product.prod_name }}</p>
                    <p>Цена: {{ product.prod_sell_price }}  ₽</p>
                </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

coursework/work/templates/work/user_orders.html
{% load static %}
{% block content %}
{% include 'header.html' %}
<div class="custom-content">
<h2>Ваши заказы</h2>
{% if orders_data %}
{% for order in orders_data %}
<h5>Номер заказа: {{ order.order_id }}.          Дата: {{order.order_date}}.
          Статус: {{ order.status }}</h5>
<table class="order">
    <thead>
    <tr>
        <th>Изображение</th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Цена за штуку</th>
        <th>Цена</th>
    </tr>
    </thead>
    <tbody>
    {% for item in order.items %}
    <tr>
        <td>
            <a href="{{ item.product.get_absolute_url }}">
                <img src="{{ item.prod_photo }} "
                     alt="Картинка скоро появится">
            </a>
        </td>
        <td>{{ item.product_name }}</td>
        <td>{{ item.amount }}</td>
        <td class="num">{{ item.price }}</td>
        <td class="num">{{ item.total_price }}</td>
    </tr>
    {% endfor %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="3"></td>
        <td class="num">{{ order.full_price }}</td>
    </tr>
    </tbody>
</table>
{% endfor %}
{% else %}
<p>У вас пока нет заказов. <a href="{% url 'welcome' %}">Вернуться к покупкам</a>.
</p>
{% endif %}
</div>
{% endblock %}

coursework/work/templates/work/user_profile.html
{% load static %}
{% block content %}
{% include 'header.html' %}
<div class="custom-content">
    <div class="user">
    <img src="{{ user.photo }}"
                     alt="Добавьте Вашу фотографию">
       <p>{{ user.first_name }} {{ user.last_name }}</p>
        <p>{{user.email}}</p>
        <a href="{% url 'user_orders' %}">Заказы</a>
        <a href="{% url 'logout' %}">Выйти</a>
    </div>
</div>
{% endblock %}