coursework/cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove,
            name='cart_remove'),
    re_path(r'^place/$', views.cart_place_order,
            name='cart_place_order'),
]

coursework/coursework/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from work import views

app_name = 'work'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.product_list, name="welcome"),

    path("users/", include('users.urls')),
    path("cart/", include('cart.urls')),
    path('category/<int:category_id>/', views.category_products,
         name='category_products'),
    path('product/<int:product_id>/', views.product_detail,
         name='product_detail'),
    path("orders/", views.user_orders, name="user_orders"),
    path("search/", views.search_products, name="search_products"),
    re_path(r'^report_builder/', include('report_builder.urls')),
    path('admin_tools_stats/', include('admin_tools_stats.urls'))
    # path('cart/', views.product_list, name="cart"),

]

coursework/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=[], coerce=int, initial=1,
                                      required=False, label='Количество')
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

    def __init__(self, max_quantity1, *args, **kwargs):
        print(f"{type(max_quantity1)}")
        super().__init__(*args, **kwargs)
        self.fields['quantity'].choices = [
            (i, str(i)) for i in range(1, min(max_quantity1, 20)+1)]

coursework/cart/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from work.models import Products
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request.user, request)
    product = get_object_or_404(Products, pk=product_id)
    max_quantity_value = product.prod_amount
    form = CartAddProductForm(max_quantity1=max_quantity_value,
                              data=request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product_id=product_id, quantity=cd['quantity'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request.user, request)
    product = get_object_or_404(Products, product_id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request.user, request)
    cart_items = cart.get_items()
    total_price = cart.get_total_price()

    processed_cart_items = []
    out_of_stock_items = []
    for item in cart_items:
        total_price_for_item = cart.get_total_price_for_item(item)
        processed_item = {
            'oi_prod_name': item.oi_product,
            'oi_product_id': item.oi_product_id,
            'oi_amount': item.oi_amount,
            'photo_url': item.oi_product.prod_photo,
            'total_price_for_item': total_price_for_item
        }
        if item.oi_amount > 0 and item.oi_product.prod_amount > 0:
            processed_cart_items.append(processed_item)
        elif item.oi_amount == 0 and item.oi_product.prod_amount == 0:
            out_of_stock_items.append(processed_item)
        elif item.oi_amount == 0 and item.oi_product.prod_amount > 0:
            item.oi_amount = 1
            item.save()
            processed_item['oi_amount'] = item.oi_amount
            processed_item[
                'total_price_for_item'] = cart.get_total_price_for_item(item)
            processed_cart_items.append(processed_item)
        elif item.oi_amount > 0 and item.oi_product.prod_amount == 0:
            processed_cart_items.append(processed_item)

    total_price = cart.get_total_price()
    context = {
        'cart_items': processed_cart_items,
        'out_of_stock_items': out_of_stock_items,
        'total_price': total_price,
    }

    return render(request, 'cart/detail.html', context)


def cart_place_order(request):
    if request.method == 'POST' and 'place_order' in request.POST:
        cart = Cart(request.user, request)
        print(f'CAAAAAAAAAAAAART{cart}')
        try:
            cart.place_order()
            messages.success(request, 'Заказ создан. Спасибо!')
        except ValueError as e:
            messages.error(request, str(e))
            # Добавляем сообщение об ошибке в случае нехватки товара

        # return render(request, 'user_orders.html',
        #               {'success': messages.success})
        return redirect(
            'cart:cart_detail')
    else:
        # Handle non-POST requests or requests without 'place_order'
        # You might want to redirect to a different page or show an error
        # message
        return redirect(
            'cart:cart_detail')  # Redirect to the cart detail page or any
        # other page
# def cart_detail(request):
#     cart = Cart(request)
#     # converted_photo = convert_to_direct_link(product.prod_photo)
#     return render(request, 'cart/detail.html',
#                   {'cart': cart})
# @require_POST
# def cart_add(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Products, product_id=product_id)
#     form = CartAddProductForm(request.POST)
#     if form.is_valid():
#         cd = form.cleaned_data
#         cart.add(product=product,
#                  quantity=cd['quantity'],
#                  update_quantity=cd['update'])
#
#         with (transaction.atomic()):
#             order = Orders.objects.filter(
#                 ord_customer=request.user,
#                 ord_status__status_name='Временный').first()
#             if not order:
#                 order = Orders.objects.create(ord_customer=request.user,
#                                               ord_status=Status.objects.get(
#                                                   status_name='Временный'))
#         for item in cart:
#             product = Products.objects.get(
#                 product_id=item['product']['product_id'])
#             order_item, created = OrderItems.objects.get_or_create(
#                 oi_order=order,
#                 oi_product=product,
#                 defaults={'oi_amount': item['quantity']}
#             )
#             if not created:
#                 order_item.oi_amount += item['quantity']
#                 order_item.save()
#
#         # request.session['added_product'] = {'prod_photo': converted_photo}
#         # print(f"{type(request.session['added_product'].get(
#         'prod_photo'))}")
#         # print(
#         #     f"Product {product.prod_name} added to the cart with quantity "
#         #     f"{cd['quantity']}.")
#         # print(f"Cart contents: {cart.cart}")
#     # else:
#     #     print("Form is not valid.")
#     #     print(form.errors)
#     # session_data = dict(request.session)
#     # print(f"{session_data}")
#     return redirect('cart:cart_detail')
#
#
# def cart_remove(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Products, product_id=product_id)
#     cart.remove(product)
#     return redirect('cart:cart_detail')
#
#
# def cart_detail(request):
#     cart = Cart(request)
#     # converted_photo = convert_to_direct_link(product.prod_photo)
#     return render(request, 'cart/detail.html',
#                   {'cart': cart})

coursework/cart/templates/cart/detail.html
{% extends "work/main.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
{% include 'header.html' %}
<div class="custom-content">
<h1>Корзина</h1>
{% if cart_items %}
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за штуку</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart_items %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ item.photo_url }} "
                         alt="{{ product.prod_name }}" width="170" height="180">
                </a>
            </td>
            <td>{{ item.oi_prod_name }}</td>
            <td>{{ item.oi_amount }}</td>
            <td>
                <a href="{% url 'cart:cart_remove' item.oi_product_id %}">Удалить</a>
            </td>
            <td class="num">{{ item.oi_prod_name.prod_sell_price }}</td>
            <td class="num">{{ item.total_price_for_item }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">{{ total_price }}</td>
        </tr>
        </tbody>
    </table>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    <p class="text-right">
        <a href="{% url 'welcome' %}" class="button light">Продолжить покупки</a>
        <form method="post" action="{% url 'cart:cart_place_order' %}">
            {% csrf_token %}
            <button type="submit" name="place_order">Заказать</button>
        </form>
    </p>
{% else %}
    <p>Ваша корзина пуста. <a href="{% url 'welcome' %}">Вернуться к покупкам</a>.</p>
{% endif %}

{% if out_of_stock_items %}
    <div class="out-of_stock-items">
    <p> Товар закончился</p>
        <table class="cart">
            <thead>
            <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена </th>
            </tr>
            </thead>
            <tbody>
            {% for item in out_of_stock_items %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ item.photo_url }} "
                             alt="{{ product.prod_name_thumbnail }}" width="170" height="180">
                    </a>
                </td>
                <td>{{ item.oi_prod_name }}</td>
                <td>Нет в наличии</td>
                <td>
                    <a href="{% url 'cart:cart_remove' item.oi_product_id %}">Удалить</a>
                </td>
                <td class="num">{{ item.oi_prod_name.prod_sell_price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}

{% endblock %}